In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import pandas as pd

In [10]:
# Get Shift Data
shift_data_file = "data/shift_data.csv"
shift_df = pd.read_csv(shift_data_file)
shift_df = shift_df.fillna(0, inplace=True)
shift_df.head()

  shift  hours
0   mlp      1
1   mlc      1
2   mpd      2
3   mdc      1
4   tlp      1

In [12]:
# Load schedule preferences of members
test_pref_data_file = "data/test_pref.csv"
test_pref_df = pd.read_csv(test_pref_data_file)
test_pref_df = test_pref_df.fillna(0, inplace=True)
test_pref_df.head()

       name  mlp  mlc  mdp  mdc
0   michlik    0    0    8    1
1    sutton    1    4    0    7
2  bessenov    0    0    6    3
3     feder    1    6    1    8
4      deac    1    1    1    1

In [ ]:
# Object with array of parameters and target function
# target function is continuous
# and a linear interpolation betwen closest discrete points
# NEED A WAY TO MAINTAIN FULFILLING REQUIRED SHIFTS
class koinSmoothFunc:
    def __init__(self, shift_df, pref_df):
        # define parameters
        # self.parameters =
        pass 
    
    # define target function
    def func(x):
        pass

In [ ]:
# define loss function for our target
# using MSE loss class:
# https://docs.pytorch.org/docs/2.11/generated/torch.nn.MSELoss.html
class MSELoss():
    def __init__(self):
        pass

In [ ]:

# Define target function
f = koinSmoothFunc(shift_df, test_pref_df)# give inputs

# Define the loss function (MSELoss) and Adam optimizer
# criterion = MSELoss()
criterion = nn.MSELoss()
optimizer = optim.Adam(f.parameters, lr=0.01)

# Sample training loop
for epoch in range(50):
  # Sample input and target
  x = torch.randn(5, 1)
  y = 2*x + 1

  # Forward pass
  output = f.func(x)
  loss = criterion(output, y)

  # Backward pass and optimization
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  # Print loss every 10 epochs
  if epoch % 10 == 0:
    print(f'Epoch [{epoch}/100], Loss: {loss.item():.4f}')